export const COMPANY_DESCRIPTIONS: Record<string, string> = {
  "402": "402 Media is a digital advertising and media company.",
  "Accrue Savings": "Accrue Savings helps consumers save towards purchases with embedded savings accounts at retailers.",
  "Array": "Array provides consumer data infrastructure for financial services.",
  "Axo Neurotech": "Axo Neurotech develops advanced neurotechnology solutions for brain-computer interfaces.",
  "Baba": "Baba (CallBaba) provides AI-powered communication and customer service solutions.",
  "BigBrain": "BigBrain is a Ground Up Ventures Fund I portfolio company.",
  "BrightHire": "BrightHire provides interview intelligence to help teams make better hiring decisions.",
  "BuildOps": "BuildOps is a commercial contractor management platform for field service operations.",
  "Covenant": "Covenant Industries provides industrial technology solutions.",
  "Daily.co": "Daily.co provides real-time video and audio APIs for developers.",
  "Dandelion Energy": "Dandelion Energy installs geothermal heating and cooling systems for homes.",
  "DemoLeap": "DemoLeap is a Ground Up Ventures Fund I portfolio company.",
  "Dialogue": "Dialogue (Space Time Media) is a media and communications platform.",
  "Dialogica": "Dialogica develops conversational AI technology.",
  "Disco": "Disco (Co-op Commerce) enables collaborative commerce between brands.",
  "Draftboard": "Draftboard is a recruitment and talent platform.",
  "Driift Holdings": "Driift Holdings is a Ground Up Ventures Fund I portfolio company.",
  "EliseAI": "EliseAI provides AI-powered communication tools for property management.",
  "Flyp": "Flyp (The Selling Company) is a managed resale marketplace.",
  "FutureLot": "FutureLot (The Builder AI) is an AI-powered platform for real estate developers and homebuilders.",
  "G2": "G2 (G2 Tech) develops defense and security technology systems.",
  "Glass Imaging": "Glass Imaging develops computational photography technology for mobile devices.",
  "Good Mvmt": "Good Mvmt is a Ground Up Ventures Fund I portfolio company.",
  "Harbinger": "Harbinger Motors develops medium-duty electric commercial vehicles.",
  "Hello Wonder": "Hello Wonder (Got Wonder) is an AI-powered research and insights platform.",
  "HyWatts": "HyWatts develops hydrogen energy solutions for industrial applications.",
  "Jones": "Jones (The Jones Agency) provides insurance compliance management for commercial real estate.",
  "Kela": "Kela (Kela Defense) provides cyber threat intelligence and dark web monitoring.",
  "Komodor": "Komodor provides Kubernetes troubleshooting and monitoring tools.",
  "Konko.AI": "Konko.AI provides infrastructure for deploying and fine-tuning large language models.",
  "Lenkie": "Lenkie provides revenue-based financing for UK small businesses.",
  "Meridian": "Meridian provides payment infrastructure solutions.",
  "Nevona.AI": "Nevona.AI develops AI solutions for enterprise applications.",
  "Openlayer": "Openlayer (Unbox) provides ML model evaluation and testing tools.",
  "OptimalQ": "OptimalQ provides customer reachability intelligence for contact centers.",
  "Ownli": "Ownli (Parked Solutions) provides consumer data monetization tools.",
  "Panjaya": "Panjaya develops AI-powered video translation and dubbing technology.",
  "Phase Zero": "Phase Zero (PropheX Ltd.) is a Ground Up Ventures Fund II portfolio company.",
  "Pillar Security": "Pillar Security (Akod Security) provides security solutions for AI and LLM applications.",
  "Pipe": "Pipe provides a trading platform for recurring revenue streams.",
  "Portless": "Portless (Daily Grabs) enables DTC brands to ship from overseas manufacturers directly to US customers.",
  "Postmoda (fka Wardrobe)": "Postmoda provides fashion resale and rental services.",
  "PreQl": "PreQl provides data transformation and analytics infrastructure.",
  "PrettyDamnQuick (PDQ)": "PDQ provides last-mile delivery optimization for ecommerce.",
  "Proov.ai": "Proov.ai provides AI-powered testing and quality assurance solutions.",
  "Real": "Real (Real Dev) provides development tools and infrastructure.",
  "Reap": "Reap provides cross-border payment solutions for businesses in Asia.",
  "Refine Intelligence": "Refine Intelligence provides AI-powered compliance and audit solutions for healthcare.",
  "Ritual": "Ritual Health Technologies provides digital health and wellness solutions.",
  "StarCloud": "StarCloud (fka Lumen Orbit) develops space-based data center infrastructure.",
  "TermScout": "TermScout (Citizn Company) provides AI-powered contract review and scoring.",
  "ThreeFold": "ThreeFold Automation develops industrial automation technology.",
  "Tolstoy": "Tolstoy provides interactive and shoppable video tools for ecommerce.",
  "TripleWhale": "Triple Whale provides data analytics and attribution tools for ecommerce brands.",
  "TrueHold": "TrueHold (American Secure Living) provides sale-leaseback solutions for homeowners.",
  "Tulu": "Tulu (Tulou Community) provides smart sharing systems for residential buildings.",
  "Unit.AI": "Unit.AI (Unit Robotics) develops AI and robotics technology.",
  "Upfort (fka Paladin)": "Upfort provides cybersecurity insurance and protection for small businesses.",
  "Weave": "Weave Platform provides AI-powered drug discovery and development tools for pharmaceutical companies.",
  "Younity": "Younity Technologies provides technology solutions for community engagement.",
  "Zealthy": "Zealthy provides affordable online healthcare services including prescriptions and consultations.",
  "Zeromark": "Zeromark develops autonomous drone interception and counter-UAS technology.",
}
