// SOI Legal Name → Portfolio Name mapping

export const FUND_I_SOI_MAP: Record<string, string> = {
  '402 Media, Inc.': '402',
  'Accrue Money, Inc.': 'Accrue Savings',
  'American Secure Living Inc. (Truehold)': 'TrueHold',
  'Array Group, Inc.': 'Array',
  'BuildOps, Inc.': 'BuildOps',
  'Co-op Commerce, Inc.': 'Disco',
  'Daily,CO.': 'Daily.co',
  'Dandelion Energy, Inc.': 'Dandelion Energy',
  'Elise A.I. Technology Corp.': 'EliseAI',
  'Glass Imaging Inc.': 'Glass Imaging',
  'Komodor, Inc.': 'Komodor',
  'PDQ Logistics Ltd.': 'PrettyDamnQuick (PDQ)',
  'Paladin Data Insurance Corp.': 'Upfort (fka Paladin)',
  'Pipe Technologies, Inc.': 'Pipe',
  'The Jones Agency Inc.': 'Jones',
  'The Selling Company, Inc.': 'Flyp',
  'Tolstoy Ltd.': 'Tolstoy',
  'Tulou Community Ltd.': 'Tulu',
  'Unbox Inc.': 'Openlayer',
  'Wardrobe Technologies, Inc.': 'Postmoda (fka Wardrobe)',
  'Younity Technologies Ltd.': 'Younity',
}

export const FUND_II_SOI_MAP: Record<string, string> = {
  'Akod Security Inc.': 'Pillar Security',
  'Axo Neurotech Inc.': 'Axo Neurotech',
  'Baba Care Inc.': 'Baba',
  'Citizn Company': 'TermScout',
  'Covenant Industries, Inc.': 'Covenant',
  'Daily Grabs Inc.': 'Portless',
  'Dialogica, Inc.': 'Dialogica',
  'Draftboard Inc.': 'Draftboard',
  'G2 Tech Ltd.': 'G2',
  'Got Wonder Inc.': 'Hello Wonder',
  'Harbinger Motors Inc. (fka Electron Transport Inc.)': 'Harbinger',
  'HyWatts Inc.': 'HyWatts',
  'Kela Defense Inc.': 'Kela',
  'Lenkie Technologies Limited': 'Lenkie',
  'Meridian North America, Inc.': 'Meridian',
  'Nevona IT Ltd': 'Nevona.AI',
  'Panjaya Technologies Ltd.': 'Panjaya',
  'Parked Solutions Inc, dba Ownli': 'Ownli',
  'Preql, Inc.': 'PreQl',
  'Proov.AI Inc.': 'Proov.ai',
  'PropheX Ltd.': 'Phase Zero',
  'Real Dev Inc.': 'Real',
  'Reap Tech, Inc.': 'Reap',
  'Refine Intelligence Ltd.': 'Refine Intelligence',
  'Ritual Health Technologies Inc.': 'Ritual',
  'Space Time Media Ltd.': 'Dialogue',
  'Starcloud, Inc. (fka Lumen Orbit, Inc.)': 'StarCloud',
  'The Builder AI Inc.': 'FutureLot',
  'Threefold Automation Technologies Ltd.': 'ThreeFold',
  'Triple Whale Inc.': 'TripleWhale',
  'Unit Robotics Ltd.': 'Unit.AI',
  'Weave Platform, Inc.': 'Weave',
  'Zealthy Inc.': 'Zealthy',
  'ZeroMark, Inc.': 'Zeromark',
}
