#!/usr/bin/env python3
"""Generate a tear sheet PDF for a portfolio company."""
import sys
import json
from datetime import datetime

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
except ImportError:
    print("Installing reportlab...", file=sys.stderr)
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "reportlab", "--break-system-packages", "-q"])
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate(data_path, out_path):
    with open(data_path) as f:
        data = json.load(f)

    company = data.get("companyName", "Unknown")
    description = data.get("description", "")
    fund = data.get("fund", "")
    health = data.get("health", "")
    metrics = data.get("metrics", {})
    investments = data.get("investments", [])

    doc = SimpleDocTemplate(out_path, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=24, spaceAfter=6)
    elements.append(Paragraph(company, title_style))

    # Fund & health
    sub = f"Ground Up Ventures — Fund {fund}" if fund else "Ground Up Ventures"
    if health:
        sub += f" | Health: {health}"
    elements.append(Paragraph(sub, styles["Normal"]))
    elements.append(Spacer(1, 12))

    # Description
    if description:
        elements.append(Paragraph(description, styles["Normal"]))
        elements.append(Spacer(1, 12))

    # Metrics
    metric_items = []
    for key in ["arr", "mrr", "runway", "headcount", "momGrowth"]:
        val = metrics.get(key)
        if val:
            label = {"arr": "ARR", "mrr": "MRR", "runway": "Runway", "headcount": "Headcount", "momGrowth": "MoM Growth"}.get(key, key)
            metric_items.append([label, str(val)])
    if metric_items:
        elements.append(Paragraph("Key Metrics", styles["Heading2"]))
        t = Table(metric_items, colWidths=[2*inch, 4*inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f0f0")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 12))

    # SOI Investment Data
    if investments:
        elements.append(Paragraph("Investment Data (SOI)", styles["Heading2"]))
        headers = ["Asset", "Date", "Shares", "Cost", "Value", "Gain/Loss", "Cost/Sh", "FMV/Sh", "% Cap"]
        rows = [headers]
        for inv in investments:
            rows.append([
                str(inv.get("asset", "")),
                str(inv.get("investmentDate", "")),
                str(inv.get("shares", "-")),
                str(inv.get("cost", "")),
                str(inv.get("value", "")),
                str(inv.get("gainLoss", "")),
                str(inv.get("costPerShare", "-")),
                str(inv.get("fmvPerShare", "-")),
                str(inv.get("pctCapital", "-")),
            ])

        col_w = [1.3*inch, 0.7*inch, 0.6*inch, 0.7*inch, 0.7*inch, 0.7*inch, 0.6*inch, 0.6*inch, 0.5*inch]
        t = Table(rows, colWidths=col_w)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#333333")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 4),
            ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 12))

    # Footer
    elements.append(Spacer(1, 24))
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey)
    elements.append(Paragraph(
        f"Generated by Christina (AI) — {datetime.now().strftime('%B %d, %Y')}",
        footer_style
    ))

    doc.build(elements)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <data.json> <output.pdf>", file=sys.stderr)
        sys.exit(1)
    generate(sys.argv[1], sys.argv[2])
